spring:
  profiles:
    active: local

server:
  port: 80
  servlet:
    context-path: /api/web/v1
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: DEBUG
    demo.echo: DEBUG
