spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch
    username: batch
    password: batch
  batch:
    jdbc:
      initialize-schema: always